### ISSUE TITLE
Best way to use ScalaLib?

### ISSUE THREAD

**Issue by bbarker** [skaldarnar/ScalaLib#3]
Is the ideal way to use this module as a dependency for other modules, or as a template for modules that intend to use Scala?

If the former, it might be useful to allow authors to configure/override this line in order to specify the lib version:

```
    includeInJar 'org.scala-lang:scala-library:2.11.7'
```

I don't know much about gradle, so any suggestions would be appreciated. Thanks!

**Comment by bbarker** [comment]
Also, running `gradlew idea` from the root Terasology project seems to overwrite build.gradle, apparently removing Scala support.

**Update** maybe not, I think I did this again and there were no issues, so either it was a one-time problem or I did something else accientally.

**Comment by skaldarnar** [comment]
Hi @bbarker, sorry for the late reply. The idea was/is to use this as a dependency when developing a new module in Scala.
The Scala version should definitely be updated, if not configurable. The overall project setup with IntelliJ is also far from optimal for Scala modules as far as I remember…

**Comment by bbarker** [comment]
Thanks @skaldarnar - I spoke with @Cervator (currently on vacation I think) about this quite a lot around December/November, and came to the conclusion that it may be best to wait until the new gradle system being worked on under Nanoware is more production-ready, before tackling this. At that point, it sounds as though the core scala dependencies will be included by some other gradle file internal the Terasology repo, but the issue for handling external dependencies (which are very popular in Scala with things like Cats/Shapeless/etc that help extend the language in fairly light but significant ways) will remain an issue to be solved.

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
